server:
  port: 8080

spring:
  profiles:
    include: jwt, bcrypt, aws, real
#    active: local
    group:
      dev: log-dev
      prod: log-prod
      test: test

logging.level:
  org.hibernate.SQL: debug
